### PR TITLE
Created database tables for pendingbookings and infobookings, databas…

### PR DESCRIPTION
**Pull request by SophieJpro**
…e changelog as well.

### CODE REVIEW

**Review by bram-jpro — COMMENTED** [review]
Bit of a general question.
What are these PendingBookings and InfoBookings? When are they used? InfoBooking I might guess would be used to block booking if a cabin is closed for maintenance or similar? Based on the structure these are almost identical to the booking table, so I wonder why these are separate tables. Could they not be a status and/or type field on the bookings table? Where type would be `REGULAR` or `INFO` and if type is `INFO` then there is not User connected. Similar for state where a booking can be either `PENDING` or `CONFIRMED` and move between these states. Depending on the use cases there might not be a need to separate type and state.

Generally, it quickly becomes complicated to store the same data in different tables. In this case we would have to check 3 different tables to make sure there are no conflicting bookings, we can not leverage database constraints to enforce no conflicts across separate tables while it is possible to do that if it is in a single table. In addition once a pending booking gets confirmed the whole row needs to be moved instead of just updating a status. So unless there is some compelling reason why these bookings need to exist in separate tables, fields on the booking table should be used instead.

**Comment by SophieJpro** [comment]
The thought behind the pending booking is that instead of getting a confirmed booking the moment you hit submit, that there will be a 7 day time period in which other employees can contest the requested dates. So if someone else also wants the same dates, they can submit an interest claim and after the 7 days a randomizer (or an admin) will pick one of the pending bookings and make them confirmed. 

The info bookings are as you thought, either used for maintainance, events or general information. 

So you mean to create new columns that contain the state of the booking? Pending/Confirmed, Regular/Info? And new column for created date? Or is field referring to something else?

**Comment by bram-jpro** [comment]
Yes, in the cases you described I think it is better to use new columns to differentiate the bookings. Yes on the createdDate as well, and since they now can be updated a updatedDate should be added as well :)

In my experience it is the easiest to work with enums for the various options in Java/Kotlin but text/varchar columns in the database and then `@Enumerated(EnumType.STRING)` on the entity-field.

**Comment by SophieJpro** [comment]
Would a boolean in the fields work as well or is enum the preferred standard? Like if the column is called "Confirmed" it is either true or false, where false then indicates that it is pending. Likewise for the column named "Regular" a regular booking is indicated with true, and false if it is an infoBooking. We would then add another column which would be a text field that would be called "Description". Here the admin can write a message if the "Regular" field is false. 

Alternatively the idea is that the infoBooking is really more of a message than it is a booking, since Roger wanted a way to notify employees about vacations, events, etc. So our thought is to separate this one from the booking table since it doesnt need employee_id or apartment_id (or any of the new fields). In this case we would not need the "Regular" field in the booking table. Is this a good alternative?

**Pull request closed without merging**
